// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';
import {embed} from '../models';
import {options} from '../models';

export function GetContext():Promise<context.Context>;

export function GetOptions(arg1:embed.FS):Promise<options.App>;

export function RegisterHotkey():Promise<void>;

export function SetContext(arg1:context.Context):Promise<void>;
